name: Run ML Pipeline

on: [push]

jobs:
  ml-pipeline-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Set up DVC
      uses: iterative/setup-dvc@v1
    - name: Pull the dataset
      run: dvc pull
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Run training script
      run: python src/train.py